url: https://raph333.github.io
#baseurl: /projects/

# Site settings
title: Raphael Peer
email: raphael1peer@gmail.com
description: "Raphael Peer - collection of Machine Learning projects"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/raphael-peer
  - title: github
    url: https://github.com/raph333
  - title: kaggle
    url: https://www.kaggle.com/rpeer333

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
